### ISSUE TITLE
Layer Mask within Layer Group affects scaling on export

### ISSUE THREAD

**Issue by adamdiestelkamp** [adobe-photoshop/generator-assets#201]
Working on a project for iOS, the developer let me know that one of my images wasn't half of the @2x image. After some tinkering I found an offending layer mask within the layer set (even if the layer and layer mask are not visible), when this layer mask is deleted the image exported and scaled correctly. Another workaround is creating a mask on the parent layer set that I'm exporting and then it will export/scale correctly. 

The two layers sets I'm comparing create identically sized @2x assets but different sized 50% scaled assets.

I can send the PSD for someone to examine the potential issue, thanks!

----------

![screen shot 2014-03-19 at 2 17 55 pm](https://f.cloud.github.com/assets/4571734/2464814/72a07af6-af9b-11e3-911e-03e4f867d4ba.png)

**Comment by pineapplespatula** [comment]
@chadrolfs  Im not seeing this in the current build. I can send you the test file if that works best

**Comment by chadrolfs** [comment]
Yep, I'm not seeing this either and the related/similar issue (40) has been closed.  Closing this as well as resolved
