### ISSUE TITLE
[DOM] Document objects should emit a "saved" event

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/generator-assets#218]
The way `imageChanged` indicates that a PSD has been saved is with the presence of the `file` property. Right now, though, we filter out these changes when the value of `file` hasn't changed. Instead what we should be doing is always emitting a `saved` event when `file` is included in `imageChanged`. We should continue to emit a `file` event only when the file path has actually changed.

This should be considered to block pulling and releasing (or advertising) the DOM in core.

**Comment by mcilroyc** [comment]
How's this going @volfied?  :walking: 
@iwehrman do you have any recollection of actual problems this is causing?

**Comment by volfied** [comment]
I'll unassign myself as I have no recollection of this issue, nor the project. I believe I was first set to work on this, but then we started spaces.

**Comment by iwehrman** [comment]
This is an API-spruce-up feature request. Which is to say, this can be closed.
