### ISSUE TITLE
Cropping is sometimes inconsistent for text layers at smaller export sizes

### ISSUE THREAD

**Issue by timriot** [adobe-photoshop/generator-assets#233]
"I had a screen grab with explanatory text around it. At large export sizes all was fine. As I got below say 40% image size I was finding that *some* exports were cropping off the text (not all did this). The only solution I could find was to put a background square in the grouped layer (i.e. under the generator export) so as to somehow force PS into thinking there was a bigger object to deal with than just the text."

I have asked for an example PSD. Waiting to hear back.

**Comment by mcilroyc** [comment]
Let me know if you hear back, @timriot
