### ISSUE TITLE
assets.generate directory in shipping PS should be renamed to generator-assets

### ISSUE THREAD

**Issue by joelrbrandt** [adobe-photoshop/generator-assets#249]
Need to do this on a non-dot-release cycle. Next opportunity is 16.0. Hope we don't forget. Again.

**Comment by mcilroyc** [comment]
Looks like we forgot, @joelrbrandt.  Can you explain why this is necessary/recommended?

**Comment by joelrbrandt** [comment]
The only reason is hygiene. This is low priority for sure. 

FWIW, the fact that the copy of generator core that ships inside PS is in a directory named "generator-Builtin" instead of "generator-builtin" or "generator-built-in" really gets my OCD wound up.

**Comment by mcilroyc** [comment]
welp, it just got three times harder since we now have three delivered plugins that follow the same naming pattern.  This might just be the new normal, joel.  I'll tack this on to the general build story I've got open - but still no guarantees.

**Comment by joelrbrandt** [comment]
thanksfor.trying
