### ISSUE TITLE
ImageMagick error: convert.exe: invalid argument for option `-extent': NaNxNaN-NaN-NaN @ error/convert.c/ConvertImageCommand/1438.

### ISSUE THREAD

**Issue by AlicanC** [adobe-photoshop/generator-assets#259]
The error:
```
[error:generator-assets 14:37:53.150 C:\Users\User\Documents\GitHub\generator-core\test\plugins\assets.generate2\lib\assetmanager.js:259:34] Render failed: image.png ImageMagick error: convert.exe: invalid argument for option `-extent': NaNxNaN-NaN-NaN @ error/convert.c/ConvertImageCommand/1438.
```

How to reproduce:
Lets say I have a 200x200 PSD. If I put a 400x400 image in it and generate, it outputs a 400x400 file. (I hate this and I have no idea why this is done like that. Why would I need the whole 400x400? I am not even seeing the rest since I am in a 200x200 file.) Since I don't want this, I select the whole document with the Rectangular Marquee Tool and mask the layer group that contains the 400x400 image so I get a 200x200 result. When I do this, generator-assets crashes.

Video of reproduction: http://youtu.be/HDPvXTQv0hM

Photoshop CC 2014.1.0
Node.js is v0.10.24
generator-core is 3.2.0-dev
generator-assets 2.0.1 (Copied the one shipped with Photoshop CC 2014.1.0)

**Comment by mcilroyc** [comment]
@chadrolfs can you validate this?  1) Seems like a fix PR was merged, and 2) It might be moot now that we use FLITE instead of imagemagic.

**Comment by chadrolfs** [comment]
It's interesting, the result without a mask is correct now (200x200) and is confined to doc bounds, however when a mask is applied, the output is the entire later and doc bounds are ignored (that's a separate bug which I think is logged wrt mask support).  I'm not seeing a crash either so this particular bug is fixed.  Closing.
