### ISSUE TITLE
The hungry hungry Asset Generator

### ISSUE THREAD

**Issue by lewishowles** [adobe-photoshop/generator-assets#268]
I've found that on occasion, the Asset Generator will output image assets (perhaps sometimes because Generate Image Assets was accidentally left on), but then decide that it doesn't want to stop. Ever.

At this minute, I'm trying to work on a document with a relatively large number of assets that were being generated - most of which were SVG. As soon as I noticed Photoshop flicking through my layers (as it seems to do when outputting SVG), I turned off Generate Image Assets - but by then Skynet had taken over and Photoshop is regularly generating assets, running through them all while I make changes - even though none of the changes affected any of the assets being generated, and, more importantly, Generate Image Assets is turned off!

One thing that might help is to make the Asset Generation toggle apply per-document, not to every open item - as if I do want to generate assets from one simple document, I have found that it then takes hold of other documents until I close Photoshop entirely.

**Comment by mcilroyc** [comment]
@chadrolfs please review this reported issue and update it if you happen to observe this behavior while testing.  Much has changed with the underlying SVG lib, so this may no longer be an issue.

**Comment by chadrolfs** [comment]
I CNR, tried with 350+ layered doc with svg and png counterparts.  Turning Generate Assets off discontinues outputting new changes to the doc.  I think this is no longer an issue.  Closing.  Please re-open if you run into this again.  Thanks.
