### ISSUE TITLE
Weird behavior with masks

### ISSUE THREAD

**Issue by blasesmith** [adobe-photoshop/generator-assets#308]
I have a weird problem with the assets generator, especially when I use masks.
I've attached an image, how I set a document. As you can see, I set 6 jpgs to be exported, but there are only 5. I have to say, that in the previous versions this was working fine, without any issue. Right now I'm using the latest Photoshop 2014.1.0. 

The missing image is the one which has a mask at 0 px from the left. If I put that mask 1 px away from the left it will be generated. Sometimes this error happens with the masks at highest levels also, such as on this sample image: i.e: layer name: image_2_mask_at_0px_from_left.jpg

![sample](https://cloud.githubusercontent.com/assets/8833253/4336325/925574c8-4005-11e4-99bd-869ea876bc5f.jpg)
masks. 

Thank you for your help. Maybe there is a solution for fix this, maybe I have to change the layout or so.

**Comment by chadrolfs** [comment]
@blasesmith thank you for the screenshot of how you constructed your file.  I did my best to replicate the folder structure, naming convention and applied masks but can not repro the problem.  Can you still reproduce this bug with the current release (2015.1.2 r355)?

**Comment by chadrolfs** [comment]
@mcilroyc I CNR and inquired if still reproducible.

**Comment by mcilroyc** [comment]
I tried with the original test file on 16.1.2 and saw 6 JPGs generated.  closing this issue.
