### ISSUE TITLE
enable pngquant by default

### ISSUE THREAD

**Issue by joelrbrandt** [adobe-photoshop/generator-assets#309]
PNGQuant is not on by default in 15.2. There are minor automation failures as reported in Watson 3799685 but manual testing indicates that PNGQuant does work on all platforms.

For 15.3 (or whatever is after 15.2) we should shoot for having this enabled by default.

cc @jhatwich Does Crema currently do anything with PNGQuant for 15.2? Do you have plans to do something in the future?

**Comment by imaderyc** [comment]
I believe this was fixed already
