### ISSUE TITLE
Problem with vector mask and layer group

### ISSUE THREAD

**Issue by Simon-Colley** [adobe-photoshop/generator-assets#323]
Vector mask applied to layer groups doesn't appear to be working as expected:

The following psd should output images using the vector masks applied (offset / with padding):

![screen shot 2014-11-04 at 11 28 24](https://cloud.githubusercontent.com/assets/1893025/4898936/2f0b04ca-6416-11e4-81fc-906b643e5d3a.png)

The images generated appear to be clipped to the shapes bounds ignoring the containing groups' vector mask:

 
![screen shot 2014-11-04 at 11 28 44](https://cloud.githubusercontent.com/assets/1893025/4898939/390f174a-6416-11e4-84b8-d5a60bf6fcff.png)

Happy to supply test psd if needed

**Comment by chadrolfs** [comment]
Hi @Simon-Colley, this appears to be working in the most recent release.  I can no longer reproduce this bug.  Are you still seeing this issue?  If not, we can close this bug.  Thanks.  CC @mcilroyc

**Comment by Simon-Colley** [comment]
Yes I can confirm that it is fixed :)

**Comment by chadrolfs** [comment]
Excellent, thank you @Simon-Colley!
