### ISSUE TITLE
Nested and global layers

### ISSUE THREAD

**Issue by knuckleswolf** [adobe-photoshop/generator-assets#326]
All greetings! Have some difficulty over the choice of layers because generator exporting there are several stages, which are difficult to catch. I Would like to clarify the situation. 

Necessary get some changes, it's really need:
- Part of the group has the sign "^" at the beginning of the name, such must be exported together with the group under him not having that character - "^".
![000007201](https://cloud.githubusercontent.com/assets/8302209/5196914/9bc49c0e-756c-11e4-91dd-9fb09342e8a0.jpg)

- Need to export not only the generator contents of groups, but common elements and layers. (eg backgrounds, caps, etc.) Common elements is visible layers that lie at the root of the psd, exported outside groups.
![2014-11-13_14481](https://cloud.githubusercontent.com/assets/8302209/5196920/b95e111e-756c-11e4-816a-9525f1177a3b.jpg)

Thanks!

**Comment by mcilroyc** [comment]
Closing this issue because the workaround (using Layer Comps) seems sufficient.  If @knuckleswolf feels otherwise, we can re-open it as a feature request.
