### ISSUE TITLE
Scaling shapes/vectors inside smart objects

### ISSUE THREAD

**Issue by hisnameisjimmy** [adobe-photoshop/generator-assets#331]
Right now (2014.2.1), if I scale a smart object with generator, it seems to be taking it as a bitmap and scaling it instead of scaling the underlying shapes or vectors contained within the smart object. 

Similar issues: https://github.com/adobe-photoshop/generator-assets/issues/322 and https://github.com/adobe-photoshop/generator-assets/issues/48

**Comment by imaderyc** [comment]
internal bug 3909740

**Comment by mcilroyc** [comment]
@pineapplespatula please review in conjunction with other SO scaling research

**Comment by pineapplespatula** [comment]
Is the Smart Object a PSD? I cannot reproduce this one. @chadrolfs  can you give it a shot

**Comment by chadrolfs** [comment]
Tried with several different smart objects, seems to be scaling correctly.  Closing.  @hisnameisjimmy please re-open if this is still happening for you with the current version of Photoshop CC.
