### ISSUE TITLE
Rendering of image assets lower quality than expected, and not matching equivalents from 'Save for Web'

### ISSUE THREAD

**Issue by JimCollinson** [adobe-photoshop/generator-assets#348]
I'm finding the image quality of generated assets is significantly poorer than expected, particularly when it comes in compression artefacts on JPEGs and also how things like text is rendered. Wondering if I'm alone in this experience. Examples below (you may have to click to view at 100% for full effect):

### Image exported via 'Save for Web (Legacy)':

![save-for-web](https://cloud.githubusercontent.com/assets/13061030/8477845/3a3b68dc-20c5-11e5-96bc-b66b5fa50fda.jpg)

The image above was saved as a JPEG: Quality 90, Blur 0, Optimised, Embedded Color Profile, sRGB with Bicubic sizing.

### Image exported via Adobe Generator

![adobe-generator](https://cloud.githubusercontent.com/assets/13061030/8477910/a4aa813a-20c5-11e5-862d-64b559d28f6d.jpg)

The image above was exported via generator with the default settings. 

Note the poor text rendering (the right of the last 0 is clipped off) and the compression artefacts, particularly around the lettering and logo. I'm also wondering about the differences in colour/profile.

Significant difference in file size too.

<br />
<br />

Here are the results with quality set to jpg8 / 80%:

### Image exported via 'Save for Web (Legacy)' 80% quality:

![save-for-web-80](https://cloud.githubusercontent.com/assets/13061030/8478052/c3d0d9fa-20c6-11e5-9730-d6d21bcad3d6.jpg)

### Image exported via Adobe Generator jpg8:

![adobe-generator-8](https://cloud.githubusercontent.com/assets/13061030/8478061/cba3162a-20c6-11e5-93a7-b07e87b41200.jpg)

<br />
<br />

And here is probably the worst example, the 32-bit PNG. Both should be identical, or so I would have thought:

### Image exported via 'Save for Web (Legacy)' PNG 32:

![save-for-web](https://cloud.githubusercontent.com/assets/13061030/8478141/54923600-20c7-11e5-8db2-8b3a5186d149.png)

### Image exported via Adobe Generator PNG:

![adobe-generator](https://cloud.githubusercontent.com/assets/13061030/8478153/6132a2c8-20c7-11e5-8443-db4f2c720bbd.png)

What's going on here? Are there some parameters that I'm missing?

Not really usable as a viable method of generating assets for the web if these are the results. For me at least.

**Comment by timothynoel** [comment]
Hi Jim, is there a chance you could send along a psd that displays the issue and/or a Generator log (~/Library/Logs/Adobe/Adobe Photoshop CC 2015/Generator)?  Is this using File->Export->Export As..? File->Generator-> Image Assets? Are these assets being scaled, and are they bitmaps?   The scaling of bitmap is affected by an Image Interpolation preference (looks like there's some excess sharpening going on, so maybe it somehow got set to a method better for reduction).  There's a free extension to set some global Generator preferences here: https://creative.adobe.com/addons/products/2274

**Comment by JimCollinson** [comment]
Hi Timothy,

Yeah, these assets are being scaled from large linked JPGs / Bitmap layered PSDs and I'm using File->Generator-> Image Assets to export.

Where should I send the logs/psd?

I'll have a look at that plugin, thanks.

**Comment by JimCollinson** [comment]
Tried using the extension you mentioned and it stopped Generator working entirely.

I've been toying around with the interpolation settings in File->Export->Export As.. and they have little to no effect on the issues I'm seeing with heavy compression artefacts. Seems to be related to JPG quality settings.

Another example here, this time using File->Export->Export As.. first, 80% quality bicubic JPG scaled down to 23.07%:

![klimax power amps - export](https://cloud.githubusercontent.com/assets/13061030/8546642/6cb47930-24b1-11e5-89e3-f64443fadf1d.jpg)

And again, from Save for web (legacy) using the same settings — 80% jpg and bicubic down sized to 23.07%:

![klimax-power-amps-save-for-web](https://cloud.githubusercontent.com/assets/13061030/8546675/b4e92246-24b1-11e5-9a18-6df31f5a6c2a.jpg)

You'll see again, the terrible compression artefacts around the text. It's more like the quality I'd expect from a 50% jpg.

**Comment by timothynoel** [comment]
You could send the psd/ Generator logs to timothynoel@gmail.com (we'll keep them internal/confidential to Adobe).  The weird thing is that it shows up in the png, too, which is why I thought it was happening in the downscaling before it gets to the file format stage (imagemagick).  Generator has it's own interpolation pref (it should default to automatic).  The psd/logs would give a better clue about what it's actually doing internally. The settings extension looks like it needs some updating for cc 2015 (or generator isn't reading the old settings properly).  I'll have to follow that up as another issue.

**Comment by JimCollinson** [comment]
Any update on this?

**Comment by timothynoel** [comment]
Not a complete solution yet.  It is scaling a smart object, so it's re-rendering the text and other layers as if you used an image size on the psd.  Which is different from save for web which just scales a flat bitmap. The smart object scaling usually results in a more accuracy, but for some reason the text isn't rendering right.  When I tried your file I didn't have the fonts in the smart objects which might explain the bad text rendering for me at least. There is a way to disable the smart object scaling in the prefs using the prefs extension panel, but that isn't working quite right as you discovered. If you don't need Export As... (and are just using Generator Image Assets...) one possible work around is to remove the crema CEP panel from /Library/Application Support/Adobe/CEP/Extensions.  Then you can switch off the smart object scale to scale the smart object as a flat bitmap

**Comment by JimCollinson** [comment]
I'm not seeing /Library/Application Support/Adobe/CEP/Extensions, is that in a different location on CC 2015? DO I need to have the prefs extension installed to see that?

Just to let you know a little more about my use case: I've got a series of PSDs generating thousands of image assets and product shots for a commercial website. So going through and using the Save for Web to output these is a mammoth task — really needs some sort of automation.

**Comment by timothynoel** [comment]
Here's the extra generator related plugins for CC 2015 and related CEP panels. After a default install:
(this is the library off the root, not your user home folder)
/Library/Application\ Support/Adobe/CEP/extensions/com.adobe.webpa.crema
/Library/Application\ Support/Adobe/CEP/extensions/com.adobe.preview 
/Library/Application\ Support/Adobe/Plug-Ins/CC/Generator/crema.generate
/Library/Application\ Support/Adobe/Plug-Ins/CC/Generator/preview.generate

**Comment by imaderyc** [comment]
this should be fixed in latest PS Update

**Comment by JimCollinson** [comment]
That's good news, although I'm not seeing it mentioned in the update release notes blog post. https://blogs.adobe.com/crawlspace/

Will have to give it a test.

**Comment by JimCollinson** [comment]
Right, I've tested this on the latests version of Photoshop (2015.1.2) and there is no change / fix. 

### Image exported via 'Save for Web (Legacy)':

![akurate-2200-save-for-web](https://cloud.githubusercontent.com/assets/13061030/12550008/e3e45e1c-c358-11e5-9d02-8f93c5233a81.jpg)


The image above was saved as a JPEG: Quality 90, Blur 0, Optimised, Embedded Color Profile, sRGB with Bicubic sizing.

### Image exported via Adobe Generator

![akurate-2200-silver-front-x1090](https://cloud.githubusercontent.com/assets/13061030/12550046/2635562c-c359-11e5-8393-244ea3cc75b2.jpg)


The image above was exported via generator with the default settings.

Note the poor text rendering (the right of the last 0 is clipped off) and the compression artefacts, particularly around the lettering and logo, differences in colour, files size etc.

**Generator images still not good enough for production use in this case. We are still relying on Save For Web.**

**Comment by chadrolfs** [comment]
The library that S4W uses is different than the library Generator uses.  We are working on adding options to be able to match the compression more accurately to achieve results that are more expected and comparable.

**Comment by nacayoda** [comment]
So if we have issues with Photoshop, should we be lodging them here instead of feedback.photoshop.com/photoshop_family these days?

**Comment by chadrolfs** [comment]
@nacayoda not necessarily.  There are a few unique places I know of for reporting issue:
For issues specific to Generator, you can certainly log those here.
For issues specific to Design Space, you can log those here: [design-space](https://github.com/adobe-photoshop/spaces-design/issues)
All other Photoshop issues/bugs, those should go to the URL you called out.

**Comment by pineapplespatula** [comment]
It looks like this is an issue with smart objects being resized recursively instead of being rendered first and then resized ( what Save for Web does).

I propose that we increase the visibility of the rendering options when it comes to smart objects, since there seem to be viable cases where each options is preferable.

**Comment by JimCollinson** [comment]
That seems to be one of the issue, but not the *only* issue. It's just not getting the same results in terms of output quality regardless of [whether smart objects are used or not](https://feedback.photoshop.com/photoshop_family/topics/generate-jpegs-very-poor-quality-from-ps-cc-2015
).

Oh, and then there is the [lack of sRGB export.](https://feedback.photoshop.com/photoshop_family/topics/generate-jpegs-very-poor-quality-from-ps-cc-2015#reply_16615215).

All of these combined mean it's just not cut out for production work (I can only use it for quick prototyping) so it is strange that it is being recommended over Save for Web at this time.

**Comment by chadrolfs** [comment]
Hey @JimCollinson we're currently working on color profile support.

**Comment by chrisbank** [comment]
@JimCollinson converting to sRGB support is in Generate-assets since the Nov 30 release. To enable it in gernerate-assets add `"icc-profile":"sRGB IEC61966-2.1" to your config file. Embedding the color profile (any color profile) is getting worked on now. The jpeg quality is improved for "Export As" now. You can enable the same jpeg rendering in generate-assets by adding `""use-flite": true` to your generate-assets config file. This will eventually be the only option in Photoshop. This is just during the transition between the two different image encoders.

**Comment by chadrolfs** [comment]
thanks for clarifying @chrisbank!

**Comment by JimCollinson** [comment]
@chrisbank Does Save for Web use flite for rendering?

**Comment by chrisbank** [comment]
@JimCollinson Save for Web uses a completely different encoder, so you can't compare settings exactly. There's a jpeg standard but it basically says there is a quality number and leaves it the implementor to interpret (it doesn't say quality X should always give result Y) so you can't ever match two different encoders exactly. Some of it you just need to look at and pick what's right for your image.

**Comment by chadrolfs** [comment]
@JimCollinson this should be addressed in our current release (2015.5, aka PS CC 2016).

**Comment by nacayoda** [comment]
Why was this issue closed?
Generate jpeg compression has NOT been fixed in Photoshop CC 2015.5.

**Comment by nacayoda** [comment]
@chrisbank - Where is the your generate-assets config file located? I'd like to try the sRGB and jpeg filtering hack you mentioned.

**Comment by chrisbank** [comment]
@nacayoda - I have a `generator.json` file in the root of my user folder. You can see all the options for where to save the file here: https://github.com/adobe-photoshop/generator-core/wiki/Generator-Configuration-File-Format

**Comment by chadrolfs** [comment]
The defaults will still exhibit the previous results, however, updates were applied to the FLITE transcoder for better jpg optimization.  You can set Generator to use FLITE with optimization via a configuration file.  Here are additional resources you can leverage to do that along with the config file setup link Chris provided above:
https://github.com/adobe-photoshop/generator-assets/wiki/Configuration-Options

**Comment by nacayoda** [comment]
I made a "generator.js" file in my user folder with only the following in it...

```
{
    "core" : {
	"icc-profile":"sRGB IEC61966-2.1",
	"use-flite": true
    }
}
```

This has not improved the Generate output.
Did I do it wrong?

**Comment by pineapplespatula** [comment]
one thing i noticed is that you used "core" instead of  "generator-assets"

try
>{
> 
>  "generator-assets":  { 
>     "icc-profile":"sRGB IEC61966-2.1",
>     "use-flite": true
>     }
> }
> 

    "icc-profile":"sRGB IEC61966-2.1",
    "use-flite": true
    }
}

**Comment by chadrolfs** [comment]
yes, what @pineapplespatula stated above and add optimal encoding:

```{
    "generator-assets":  { 
    "use-flite":true,
    "embed-icc-profile":true,
    "icc-profile":"sRGB IEC61966-2.1",
    "use-jpg-encoding":"optimal"
    }
}```

**Comment by nacayoda** [comment]
Thanks, but it still doesn't improve the output.
I've got the generator.js file in my User Folder (C:\Users\[user-folder]\generator.js).
Should it be in an AppData folder or something?

**Comment by chadrolfs** [comment]
@nacayoda if it's a .js file, you'll need to add `module.exports=`

```module.exports = {
    "generator-assets":  { 
    "use-flite":true,
    "embed-icc-profile":true,
    "icc-profile":"sRGB IEC61966-2.1",
    "use-jpg-encoding":"optimal"
    }
}```

**Comment by nacayoda** [comment]
**IT WORKS! I've got a decent looking JPEG output... which is hopefully sRGB!**

## So, to summarise, all in one post:

To force Photoshop CC 2015.5 (Windows PC) Generate to use the new Flite export system AND as sRGB you need to:

- Create a "generate.js" file in your C:\Users\<currentUser>\ folder (location may vary)
This C:\Users\<currentUser>\generate.js file (attached in .zip format) should contain:

```
module.exports = {
    "generator-assets":  { 
    "use-flite":true,
    "embed-icc-profile":true,
    "icc-profile":"sRGB IEC61966-2.1",
    "use-jpg-encoding":"optimal"
    }
}
```
[generator.js.zip](https://github.com/adobe-photoshop/generator-assets/files/358356/generator.js.zip)

That's it. 
Launch Photoshop and start using Generate for the creation of web assets in sRGB format and with decent JPEG performance.

Thanks helpers!

**Comment by weltyry** [comment]
this is a fantastic solve. How does anyone know how I can implement it on a mac?

**Comment by iwehrman** [comment]
@weltyry The same instructions should work on Mac, but with the file at `/Users/<username>/.generator.js`. More info on config file locations here: https://github.com/adobe-photoshop/generator-core/wiki/Generator-Configuration-File-Format#config-file-locations
