### ISSUE TITLE
Image dimension issue at 200% (not exactly 200%)

### ISSUE THREAD

**Issue by idflood** [adobe-photoshop/generator-assets#350]
Hi,

The generator assets saved to our team a lot of times but since the CC 2015 update the generator doesn't behave like before.

When exporting icons to normal and double resolution we need to have consistent image resolution. But the size is most of the time wrong since the update. For instance with the exemple psd provided below:

Expected: 30 x 34 at 100%, 60 x 68 at 200%
Result: 30 x 34 at 100%,  **60 x 66** at 200%

On some assets we even get odd values in the 200% version.

Here is an exemple psd to reproduce the issue: http://cl.ly/3h321l3d3G2t

**Comment by idflood** [comment]
maybe related: https://github.com/adobe-photoshop/generator-assets/issues/160 https://github.com/adobe-photoshop/generator-assets/issues/168

**Comment by danielhusar** [comment]
+1

**Comment by imaderyc** [comment]
@danielhusar could you email us your PSD files so we can take a look? imaderyc@adobe.com

**Comment by shingo2000** [comment]
I have same issue too.

PSD file:
https://www.dropbox.com/s/n1b7xwui5kxm1wi/test_psd.zip?dl=0

generated image: /android/xxxhdpi/tab_roulette_on.png
Expected: 116 x 96 at 100%, 232 x 192 at 200%
Result: 116 x 96 at 100%, 232 x **191** at 200%

**Comment by imaderyc** [comment]
Thank you!

**Comment by imaderyc** [comment]
watson  bug 4080073

**Comment by chadrolfs** [comment]
4080073 closed/deferred with no comment or reason why it was deferred.

**Comment by chadrolfs** [comment]
I can still repro in current builds.  @mcilroyc looks like clipping is happening at the bottom, even generating at 100% it clips 2px off the height.

**Comment by pineapplespatula** [comment]
It looks like the bug was worsened when we started using approximate bounds for more of the cases. In the case that the layer is a shape layer i think we should go back to exact bounds.

**Comment by pineapplespatula** [comment]
The bug as written though i am less sure about. the included image seems to have a 32 px height with 1 px of padding on each side ( 32*2 + padding  is 66 not 68) if we expect scaled objects to have the padding scaled as well that may be a Photoshop Core Issue

**Comment by pineapplespatula** [comment]
This bug as written is misleading, The actual size of the asset is very close to 30x32 . the small amount of pixels that are created outside of that region are reflected in the exported image sizes being 2 rows of "buffering" pixels which make the images taller than the 30x32 and 60x64 that most closely maps to the image.

**Comment by mcilroyc** [comment]
FBNC to @chadrolfs in generator branch as of CL 1075853

**Comment by mcilroyc** [comment]
Note that the given test file should now produce assets at
30x34 and 60x66 *without clipping the image*

**Comment by chadrolfs** [comment]
🎉 👍

**Comment by chadrolfs** [comment]
looks good, works good!
