### ISSUE TITLE
Illustrator generator?

### ISSUE THREAD

**Issue by danielbayley** [adobe-photoshop/generator-assets#353]
Why isn't there such a thing? At the moment all of the projects I build end up as `.ai` files embedded/linked into Photoshop `.psd`s, and the only real reason for that is to make use of generator. Why not just cut out the middleman here? (I suspect also that Photoshop's image export is of a higher standard than Illustrators is?)

This kind of logic always leads me to the same ultimate question though; why doesn't Adobe just merge Photoshop & Illustrator already, and InDesign for that matter.

**Comment by mcilroyc** [comment]
That is a great suggestion, but out scope for this bug repository.  Logging the request here would be better: http://www.adobe.com/products/wishform.html

closing this issue.

**Comment by iwehrman** [comment]
@danielbayley @mcilroyc I can provide a little more background. We've talked to the Illustrator team about Generator-like functionality in the past. They're interested, but unsurprisingly they have a lot of other work on their backlog to prioritize. Registering your wish at the URL above is a great way to help them with that prioritization. Customer demand is weighed a lot more heavily than suggestions from other engineers internally!

**Comment by danielbayley** [comment]
Iv’e already written a script that outputs assets based on layer names. It’s not 100% bug free yet, isn’t quite as full-featured as the Photoshop counterpart and obviously doesn’t run automatically, but it works pretty well so far.
