### ISSUE TITLE
generator.js file stops working, how to set defaults?

### ISSUE THREAD

**Issue by thinkMichel** [adobe-photoshop/generator-assets#373]
Searching the issue list it seems like the only option to change some default settings (specifically the interpolation) is now broken in 2015? Is there any way to set the interpolation again?

The automatic interpolation makes a mess of 'hard edges'  when scaling down to 33.33%. My only alternative would be to manually scale the document to each file size. and then copy/paste the generated files.. I was hoping to use the default layer to automatically generate drawable-mdpi, hdpi, xhdpi etc folders based on a single file..

**Comment by joelrbrandt** [comment]
@isonno could you please give @thinkMichel a status update on the generator configuration file woes? I _think_ it's the case that manually created config files work? And I _think_ its the case that the overall problem associated with using the panel to create configs will be fixed in the next release? But, I can't seem to find certain confirmation of that.

**Comment by chrisbank** [comment]
Do you know that the interpolation is automatic? From the code it looks like the config files still work and by default the interpolation is ```undefined``` so it will just use the setting in the PSD

**Comment by thinkMichel** [comment]
Hi guys, thanks for all the replies. What i know is: if i use the plugin ui that generates a generator.js file (with formatting => module.exports etc) no new images are generated. I tried rebooting photoshop, also tried to replace the generator.js with a generator.json with the json markup as specified in the wiki, again with interpolation set to a specific value. This also seems to break the image generator as again no images are created.

Perhaps my config file is wrong? If anyone has a confirmed working config file, i would love to test that.

I am not sure if the default interpolation is automatic, but i recall to have read something along those lines in the documentation.

If it takes the setting in photoshop, which setting would that be? the one on Image-> Image Size?

Below is a test i did, the Image Size was set to nearest neighbor. On the left the image generated by image generator. On the right the image that was manually resized (using nearest neighbor). As you can see they are quite different when zoomed in.

![test_gernerator](https://cloud.githubusercontent.com/assets/813869/10687369/eaa00516-796c-11e5-81c5-5cf838ad5ded.png)

**Comment by isonno** [comment]
Watson claims this is fixed: https://watsonexp.corp.adobe.com/#bug=4010097

**Comment by chadrolfs** [comment]
Yes, this looks to be working correctly now in the most current release.  @thinkMichel please re-open with comments if you are still seeing this.
