### ISSUE TITLE
layer comps: asset is exported in original size when size is specified without 'px' after value

### ISSUE THREAD

**Issue by imaderyc** [adobe-photoshop/generator-assets#387]
1. name layer comp 200x200 one.png (no px after 200)
2. File->Generate->Image Assets
3. check size of the asset

Result: it's original size of layer, not 200x200
also size is not correct when syntax is like ?x200 comp3.png (198x200 instead of 200 by 200)
works if units are specified (200pxx200px)
works on layers

**Comment by Milewski** [comment]
+1

**Comment by Milewski** [comment]
in my case it doesnt even work adding px to the end... it always get a number which i dont even know where come from...

**Comment by Milewski** [comment]
okay i got i figured out the bug... if the picture... is bigger than the document... it get weird and doesnt export it right... but if u crop everything that are out of visibility then it`s get exported right...

**Comment by Milewski** [comment]
or at least wrap everything in a mask... so it will work :)

**Comment by henrikhelmers** [comment]
I am experiencing this issue. Doing a "quick export as PNG" gets the size right, and after a restart Photoshop Generator seems to figure it out as well. I also have massive shape layers that extend beyond the exported area, but they are cropped by a shape mask and also restricted by the artboard size. My "named folder" is an artboard, and the names are akin to `1024x1024 train_1024.png`.

**Comment by mcilroyc** [comment]
This is included in master and 2.6.1.  @chadrolfs note that a separate bug was spun of for the `?x200` issue.  As of now, both `200x200` and `200pxx200px` should work.

**Comment by chadrolfs** [comment]
verified fix in latest builds (mac/win)
