### ISSUE TITLE
Layer names that start with '+' throws error, may prevent further asset generation

### ISSUE THREAD

**Issue by mcilroyc** [adobe-photoshop/generator-assets#388]
Layers beginning with "+", for example "+1" generates an error message: 
> layer "+1": Expected Either a default asset specification or a layer asset specification but "+" found.

In some cases, this is reported to prevent further asset generation.

It remains to be determined what other set of initial characters might also result in errors.  

The was reported [here](http://feedback.photoshop.com/photoshop_family/topics/generator-bug#topic_6898713).

**Comment by pineapplespatula** [comment]
I cannot reproduce this preventing the generation of further assets.  If we want to try and change the parser to give better feedback for layers that begin with a delineator we can do that.

**Comment by chadrolfs** [comment]
CNR with pg builds (1047-win pg-dev, 1831-mac staging)

**Comment by mcilroyc** [comment]
Closing this because "+" is a reserved symbol in generator-asset syntax, so the reported errors are expected.  This does not seem to prevent other assets from being exported.
