### ISSUE TITLE
Bug with Asset Export when Resized

### ISSUE THREAD

**Issue by winkelsdorf** [adobe-photoshop/generator-assets#389]
I don't know if this is the right way to report this for the Adobe Asset Generator, but anyway:

Using Adobe Photoshop CC, latest Update as of today. 

**Problem**
When I enlarge a Canvas (centered resize), Assets exported afterwards are cropped. Closing and re-opening the PSD file fixed the Asset Export.

See attached screenshots.

<img width="1214" alt="screenshot 2016-01-25 22 10 34" src="https://cloud.githubusercontent.com/assets/1413291/12564961/7646c46c-c3b2-11e5-8aa1-cc1acde7ea3c.png">
<img width="174" alt="screenshot 2016-01-25 22 11 03" src="https://cloud.githubusercontent.com/assets/1413291/12564962/79224ce2-c3b2-11e5-9a75-fd71d64c8bf7.png">

**Comment by mcilroyc** [comment]
repro: 
1) open attached file, turn on asset generation, note Group 1.png is rendered correctly
2) Image > Image Size ...  >  change width to 4000 (height linked proportionally)
3) Group 1.png will be rendered incorrectly (offset/clipped)

[389-test.psd.zip](https://github.com/adobe-photoshop/generator-assets/files/117630/389-test.psd.zip)

**Comment by winkelsdorf** [comment]
@mcilroyc Yes, exactly. Good reproducible example, I didn't thought about attaching a psd here. Thank you!

P.S.: Nice hand-drawn smiley ;)

**Comment by mcilroyc** [comment]
The fix is in master and 2.6.1 (internal: and built into pg-dev mac 1082)

**Comment by chadrolfs** [comment]
verified fix on both mac and win.

**Comment by winkelsdorf** [comment]
@mcilroyc @chadrolfs Thank you!
