### ISSUE TITLE
Specifying exact output resolutions may cause distortion and incorrect bounds

### ISSUE THREAD

**Issue by AVOlight** [adobe-photoshop/generator-assets#391]
how does one specify exact output resolutions?

image size 1860x900

the percentages don't always match up
16.67% Wide310x150Logo.scale-100.png8  (outputs desired resolution)
66.67% Wide310x150Logo.scale-400.png8 (outputs 1240 x 599 resolution)

how can i use something like this
310px x 150px Wide310x150Logo.scale-100.png8
1240px x 600px Wide310x150Logo.scale-100.png8

**Comment by mcilroyc** [comment]
@AVOlight,

1. It would be helpful if you could provide a sample PSD that includes an 1860x900 layer that does not output correctly at 66.67%.
1. As a test, try nudging the layer up/down so that it lines up with a whole pixel (if doesn't currently)
1. The syntax you described for exact pixels *should* work.  Are you suggesting that those last two layer names you listed are exporting at full scale?

**Comment by AVOlight** [comment]
@mcilroyc Thank you for checking on this

[Example.zip](https://github.com/adobe-photoshop/generator-assets/files/128625/Example.zip)

**Comment by mcilroyc** [comment]
@AVOlight, thanks for your example file.  When I run it, see:
- The "a" file output correctly at 1240x600
- The "b" file however looks very bad; it is 1180 × 512 and misshapen.  

Can you confirm your same results?  If so, I'd like to rename this bug to track the "b" scenario (explicit height/width scaling) here.

**Comment by AVOlight** [comment]
@mcilroyc yes
i would very much like the ability to specify exact image size in pixels
this will save me so much time compared to using "Save for Web" and setting image size individually
Thank You

**Comment by pineapplespatula** [comment]
The resolution of this file is set to 118.11, I'm guessing that we handle this incorrectly and assume 72 ppi

**Comment by AVOlight** [comment]
sorry i don't know, i thought ppi only matters for printing
tried changing it to check, but still same result

**Comment by chadrolfs** [comment]
@AVOlight please try with latest 2015.5 release.  This should be resolved.  Please confirm.  Thanks.

**Comment by chadrolfs** [comment]
Closing as fixed.  @AVOlight Please re-open if you are still seeing this.
