### ISSUE TITLE
Layer comps scaled with ?x200: output may be off by one pixel

### ISSUE THREAD

**Issue by mcilroyc** [adobe-photoshop/generator-assets#394]
The layer-comps automation test is passing, but one small issue is hidden within.  As originally reported as a side-note to #387, in this case the output is 200x199.  This may have to do with layer effects, as it is not reproducible with an extremely simple case.

![ss](http://cl.ly/1B1a1o171L1Y/Image%202016-02-18%20at%2011.23.06%20AM.png)

**Comment by pineapplespatula** [comment]
This is likely related to our not handling layer effects correctly in our own bounds model. (which is part of why i think we should let PS tell us exact bounds more often)

**Comment by pineapplespatula** [comment]
I think this is fixed in the latest build

**Comment by chadrolfs** [comment]
Using the layer-comps.psd g-a-a test file, this looks fixed with the latest builds. 🎉
