### ISSUE TITLE
Hidden layers with outer stroke with not exporting at correct pixel dimensions

### ISSUE THREAD

**Issue by iamstannard** [adobe-photoshop/generator-assets#398]
A text layer (with outer gradient stroke) exports fine when the layer is visible.

![image](https://cloud.githubusercontent.com/assets/12769646/13519662/ade8f5d6-e22d-11e5-805b-dd834edaf780.png)

But on a layer comp where the same text layer is hidden, the png exports at the pixel dimensions of the text (not the pixel dimensions of the text + the stroke).

![image](https://cloud.githubusercontent.com/assets/12769646/13519678/cd22348a-e22d-11e5-8772-b7451c703f7e.png)

**Comment by pineapplespatula** [comment]
It looks like an issue of exact bounds being needed in this case.

**Comment by pineapplespatula** [comment]
@chadrolfs  can you regress this ( i'm not sure if this is fixed in master or just my branch)

**Comment by chadrolfs** [comment]
I thought this was the same as https://jira.corp.adobe.com/browse/PS-2286
but that bug still repro's on the latest generator build (264) but this one does not!  :confused:

**Comment by chadrolfs** [comment]
I can repro this on mac genr.264.  Lemme know if you need a test file

**Comment by chadrolfs** [comment]
verified fix in latest builds
