### ISSUE TITLE
Layer masks create pixel padding

### ISSUE THREAD

**Issue by timriot** [adobe-photoshop/generator-assets#40]
#### Designers need a way to define pixel padding.

@timothynoel has added a layer mask property to doc info and the imageChanged subscriptions which gives you the mask bounds. It should be possible to composite a document of transparent pixels with the dimensions of the mask bounds beneath the layer data using the ImageMagik command _composite_.

Here's an example of the ImageMagik command: 
composite -compose atop -geometry -13-17 white-highlight.png red-circle.png red-ball.png

**Comment by makc** [comment]
this workaround does no longer works in PS 2014.2.1, as it seems.
![screen shot 2015-05-11 at 0 18 29](https://cloud.githubusercontent.com/assets/242577/7556508/ca670d06-f773-11e4-90c5-ffbb171173aa.png)
this mask is totally ignored for me.

**Comment by makc** [comment]
hmm, I cropped the document to its full size and suddenly the mask works.

**Comment by GitterHubberGreg** [comment]
Awesome. Generate Image assets with masks works a treat.
