### ISSUE TITLE
Not changing export assets document with generator.json

### ISSUE THREAD

**Issue by abnersajr** [adobe-photoshop/generator-assets#400]
I`m trying to change my destination of image assets using a json.
I use windows 7 and created in "%USERPROFILE%/.generator.json" and  "%USERPROFILE%/.generator/.generator.json"
And nothing happen. Still creating the assets in same folder of psd file.

I would like to create the assets in a folder on desktop with the same name as generate by default.

**Comment by mcilroyc** [comment]
what are the contents of the json file you are using?

**Comment by mcilroyc** [comment]
This seems to be working with the `base-directory` property described here: https://github.com/adobe-photoshop/generator-assets/wiki/Configuration-Options

Please re-open if you can provide a counter-example @abnersajr
