### ISSUE TITLE
assets are not created when layers are in a folder

### ISSUE THREAD

**Issue by webmarss** [adobe-photoshop/generator-assets#419]
When I use Adobe Generator, only SVG files are always created without a problem. JPGs, GIFs and PNGs are only created when their layer is not in a folder. Is there a way to fix this?
<img width="2129" alt="schermafbeelding 2016-10-19 om 12 38 15" src="https://cloud.githubusercontent.com/assets/22933973/19515742/fc275bfa-95f8-11e6-95bd-eee71040c5a2.png">

I would be happy to share the PSD, which I only made to test and demonstrate this issue, but the uploader doesn't support PSDs.

Thanx,

Marcel

**Comment by chadrolfs** [comment]
@webmarss this was a bug that was introduced in PS 2015.5 and fixed in 2015.5.1.  Updating to the current version of Photoshop will resolve that problem.  Closing this but please re-open if you still see a problem after updating PS.

**Comment by webmarss** [comment]
Thanks for the quick response. The update did the trick :)
