### ISSUE TITLE
Outdated NPM Version

### ISSUE THREAD

**Issue by Milewski** [adobe-photoshop/generator-assets#429]
Can someone push the v 2.8 to npm? currently its 2.7.3 

i am annoyed with the console.time() in the renderer.js (which seems to exist only on the npm version) any reason why? 

```
(node:29605) Warning: No such label 'render' for console.timeEnd()
(node:29605) Warning: No such label 'render' for console.timeEnd()
(node:29605) Warning: No such label 'render' for console.timeEnd()
```

**Comment by mcilroyc** [comment]
@Milewski Here's my only concern: v2.8 is not certified on the shipping version of Photoshop.  Instead, I pushed a version 2.7.4 to version to npm to force an update.  It does appear that there was a flaw in the previous *npm version* that throws that warning.  Let me know if this does not appear resolved in 2.7.4
