### ISSUE TITLE
cc Photoshop 2017 Frame animations not rendered in gif

### ISSUE THREAD

**Issue by Sajaki** [adobe-photoshop/generator-assets#430]
i'm using Photoshop CC 2017 and my frame animations in the smart object are not getting exported to the generated gif. So the gif is just a static image.

**Comment by chadrolfs** [comment]
Hi @Sajaki.  Yes, currently generator does not support animated gif assets, so what you're seeing is expected at this point.  In the meantime, please use Save for Web for animated gif export.
