### ISSUE TITLE
Using generator assets in custom plug in 

### ISSUE THREAD

**Issue by javierdlg** [adobe-photoshop/generator-assets#450]
I want to use this script with a plug in that I'm making so that I can specify a file size. Can this script he called from my plugin? I'd so, is there an api for it?

**Comment by mcilroyc** [comment]
It is possible to use this repo (generator-assets) as a dependency in your plugin.  An old example is here: https://github.com/adobe-photoshop/generator-spaces

You could also consider forking this repository and adding your file-size logic

the 2.9 branch is the most stable

further questions can be asked here:
https://groups.google.com/forum/#!forum/adobe-generator-dev
